frame.title=Display Settings for {0}

button.browser=Browse
button.decode=Decode Assets
button.encode=Encode Assets
button.ok=Continue
button.cancel=Cancel

checkbox.server=Manage Server?
checkbox.light=Advanced Lighting?
checkbox.fullscreen=Fullscreen?
checkbox.vsync=Vsync?
checkbox.gamma=Gamma correction

label.serverroot=Server Directory:
label.clientroot=Client Directory:
label.resolutions=Screen Resolution
label.colordepth=Color Depth
label.refresh=Refresh Rate
label.antialias=Anti-Aliasing
label.renderdistance=Render Distance

antialias.disabled=Disabled
refresh.na=n/a

error.unsupportedmode=Your monitor reports that it does not support the display mode you've selected.\nThe combination of bit depth and refresh rate is not supported.
error.clientrootnull=Client path is not set correctly. The program will not be able to display 3D models properly. Please reconfigure.
error.serverrootnull=Server path is not correct. Cannot load server data normally.\nStart in client-only mode?
